name: Continuous Integration

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies using yarn
        run: yarn install --frozen-lockfile

      - name: Run test
        run: yarn test
